### PR TITLE
use xpath instead of iteration through the dom

### LINKED ISSUE #83: Failures details in default testsuite not reported due to core unit test changes
I noticed yesterday that errors/failures were not showing the specific failures in the single-result view properly. Example:
https://make.wordpress.org/hosting/test-results/r44742/wpdevbot-r44742/

In https://core.trac.wordpress.org/changeset/43768 we added unit tests for the new autosave REST API endpoint. Because of the `DOING_AUTOSAVE` polluting tests, they had to be separated out and run last. This essentially leads to two root level testsuites, which `process_junit_xml()` isn't accounting for. 

image

There is a core ticket for addressing the unit tests specifically, but wondering if we should better handle it here to be less brittle too. https://core.trac.wordpress.org/ticket/45132

### PR DESCRIPTION
**Pull request by pfefferle**
fix #83

### CODE REVIEW

**Comment by pfefferle** [comment]
It seems to work: https://make.wordpress.org/hosting/test-results/r47556/ionosbot-r47556/

**Comment by getsource** [comment]
I like this, but I'm wondering about your comment here: https://github.com/WordPress/phpunit-test-runner/issues/83#issuecomment-606730708

Could you please provide (maybe on that ticket directly?) an example test result so I can help take a look?

**Comment by pfefferle** [comment]
As discussed in the slack, safly I can't provide the file, I had issues with, because this problem solved :(

**Comment by getsource** [comment]
Thanks so much! Looks to work as expected in testing.

**Pull request merged**
