### PR TITLE
Report more PHP extensions

### PR DESCRIPTION
**Pull request by swissspidy**
Based on https://make.wordpress.org/hosting/handbook/server-environment/#php-extensions

Plus also `gettext` and `intl` to inform decisions about potential future i18n enhancements in core

### CODE REVIEW

**Comment by swissspidy** [comment]
@pfefferle perhaps you can help me review this one?

**Review by javiercasares — APPROVED** [review]

**Comment by swissspidy** [comment]
> (Maybe we can combine it with #134)

I'm all for it, but it sounds like further testing was requested there as it also requires changes to the reporter. Whereas this one here doesn't.

> One issue: We have no update mechanism so that hosters will get the latest changes automatically.

Is there a way to at least announce new updates to hosters, perhaps with a post on make/hosting or so?

**Comment by javiercasares** [comment]
I did a thing I'm using to do my tests
https://en.wpsysadmin.com/hosting/#el-script-que-ejecuta-todo

We have this as a project to update the official info in our Handbook.

**Review by desrosj — APPROVED** [review]
> One issue: We have no update mechanism so that hosters will get the latest changes automatically. Maybe we have to discuss that in the next office hours @javiercasares

This has been on my mind. I've created #188 with my rough thoughts there. But, after we decide on a way forward, we should definitely perform outreach starting with a post on the Make WordPress Hosting blog that details all the recent changes and what everyone needs to do in order to update.

As for this PR, I think it makes sense to go ahead and merge this. #134 is somewhat related in that it relies on PHP extensions being present, but the information reported there is more configuration specific.

**Pull request merged**
