### PR TITLE
Remove shell exec convert

### LINKED ISSUE #65: Support both ImageMagick and GraphicsMagic
GraphicsMagic is an improved fork of ImageMagic. WordPress works with both and this tester should support both of them. Currently it does not, because it runs `convert` and `convert --version` and not at all `gm convert` or `gm version`.

### PR DESCRIPTION
**Pull request by mrxkon**
Fixes #65

This removes the `imagemagick` reporting under `system_utils` as the Package information isn't actually needed.

`imagick` php_module is already reported earlier in the same array. `convert` isn't always present on systems since the imagemagick package might not be installed along the php_module.

### CODE REVIEW

**Review by rafalkukla — COMMENTED** [review]
This PR has solved my problem to the - https://github.com/WordPress/phpunit-test-runner/issues/149

https://make.wordpress.org/hosting/test-results/r51329/forgetwpbot-r51329/

**Review by pfefferle — APPROVED** [review]
Just tested it on our environment and it seems to work fine!

**Comment by pfefferle** [comment]
Thanks @mrxkon :)

**Comment by pfefferle** [comment]
and thanks for testing @rafalkukla

**Comment by rafalkukla** [comment]
> and thanks for testing @rafalkukla

Glad to help

**Pull request merged**
